### ISSUE TITLE
Specializovaný externí term exportován z Modelio do glosáře jako literál

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ssp#10]
Pokud prvek P specializuje externí term T, pak z Modelio exportujeme

P rdfs:subClassOf "T"@cs .

Měli bychom

P rdfs:subClassOf T .

Příklad je Má kód typu datové schránky z A-SGOV-104 (nutno stáhnout aktuální SGOV.zip k RPP):

a-sgov-104-pojem:má-kód-typu-datové-schránky
        a                <http://www.w3.org/2004/02/skos/core#Concept> ;
        rdfs:subClassOf  "http://www.w3.org/2004/02/skos/core#notation"@cs ;

**Comment by psiotwo** [comment]
done.

**Comment by martinnec** [comment]
Zkontrolováno na RPP.
