### ISSUE TITLE
Problém při generování OWL full/compact v případě specializace Z-SGoV/V-SGoV

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ssp#11]
Pokud model obsahuje prvek specializující prvek Z-SGoV / V-SGoV, generování OWL reprezentace spadne. Příkladem je Agenda v 111-2009, která specializuje objekt práva z V-SGoV.

**Comment by psiotwo** [comment]
Vyřešeno. 

Nově je třeba nainstalovat z [1]:
- novou verzi pluginu do Modelia
- nové verze slovníků ZSGoV a VSGoV
[1] https://drive.google.com/open?id=1t86vAVcNVpBpij9I4FiV8ZULXVRtOnMG
