### ISSUE TITLE
Doména http://onto.fel.cvut.cz/

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ssp#112]
Neměli by být prvky s IRI v doméně http://onto.fel.cvut.cz/ , které potřebujeme pro SGoV v doméně slovník.gov.cz? Např. http://onto.fel.cvut.cz/ontologies/slovník/agendový/popis-dat/pojem/slovník apod?

**Comment by psiotwo** [comment]
Ono to tak původně bylo. Je to teď takto z důvodů kompatibility všech verzí TermItu, které provozujeme. 
Osobně bych to teď neřešil, budeme to mít na paměti při produkčním nasazení.

**Comment by psiotwo** [comment]
Tento ticket zavírám - výskyty onto.fel.cvut.cz jsou pouze na "https://onto.fel.cvut.cz/ontologies/slovník/agendový/popis-dat/" - tuto ontologii využíváme jako obecný slovník pro popis datových zdrojů.
