### ISSUE TITLE
A_PSP Má obecný typ funkce špatně namodelován

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ssp#13]
"Má obecný typ funkce" v A_PSP je intrinsic trope type. Nemá být relator? Prvním účastníkem by byl Typ funkce, druhým Obecný typ funkce.

Dále je uvedeno, že specializuje rdfs:label, což je divné. Hodnota té vlastnosti "Má obecný typ funkce" je číselný kód, takže to asi nebude label ne?

**Comment by psiotwo** [comment]
Má smysl nechávat pro případné budoucí oživení modelování agendy PSP?

**Comment by psiotwo** [comment]
Nyní nerelevantní - při modelování agendy bude třeba revidovat celý model.
