### ISSUE TITLE
Specializace mezi typy objektu Osoba a Poslanec

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ssp#15]
Poslanec specializuje osobu, ale osoba by neměla specializovat poslance. V datech PSP jsou i osoby, které nejsou poslanci.

**Comment by psiotwo** [comment]
Má smysl nechávat pro případné budoucí oživení modelování agendy PSP?

**Comment by psiotwo** [comment]
Nyní nerelevantní - při modelování agendy bude třeba revidovat celý model.
