### ISSUE TITLE
Cyklus v importech slovníků Věci a Digitální objekty

### ISSUE THREAD

**Issue by blcham** [opendata-mvcr/ssp#157]
"Věc" a "Digitální objekt" jsou definovány ve vlastních slovnících "Věci" a "Digitální objekty". Obe tyto oběkty na sebe ukazují a tedy  plati:

```
g-sgov:věci/model   owl:imports    g-sgov:digitální-objekty/model  .
g-sgov:digitální-objekty/model   owl:imports    g-sgov:věci/model  .
```
Stejny cyklus tedy plati i mezi glosarmi.

![Selection_257](https://user-images.githubusercontent.com/3962237/97410851-dab5b280-18ff-11eb-8630-b93d37611f6a.jpg)

**Comment by psiotwo** [comment]
Tento cyklus již neexistuje.
