### ISSUE TITLE
Kardinality u Má obecný typ orgánu a Má nadřazený typ orgánu

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ssp#16]
Kardinality říkají, že typ orgánu má max 1 nadřazený a max 1 obecný typ orgánu, což je OK. Obráceně ale říkají, že typ orgánu má max 1 podřazený a max pro 1 je obecným typem, což asi není OK. Podle mého názoru tam má být v obráceném směru 0..*.

Podobná situace je také u Má nadřazený orgán, Má typ orgánu (současná podoba kardinalit specifikuje, že daného typu může mít max 1 orgán).

**Comment by psiotwo** [comment]
Má smysl nechávat pro případné budoucí oživení modelování agendy PSP?
