### ISSUE TITLE
Má obecný typ funkce jako typ vztahu místo typ vlastnosti

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ssp#17]
Má obecný typ orgánu je modelován jako typ binární vztahu, v němž z obou stran participuje Typ orgánu. Navrhuji modelovat Má obecný typ funkce stejně, tj. jako typ vztahu, v němž z obou stran participuje Typ funkce. Já myslím, že sémanticky to tak v PSP i mysleli, jen si usnadnili práci a udělali to tak, že obecné typy funkcí zakódovali do hodnot místo do řádků v tabulce typ_funkce. 

V RDF datech pak můžeme přidělat 3 specifické typy funkcí pro tyto obecné typy funkcí.

**Comment by psiotwo** [comment]
Má smysl nechávat pro případné budoucí oživení modelování agendy PSP?
