### ISSUE TITLE
Chybí vztah mezi typem funkce a typem orgánu

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ssp#18]
Podle dokumentace otevřených dat PSP ČR http://www.psp.cz/sqw/hp.sqw?k=1301, přesněji podle dokumentace tabulky typ_funkce, je typ funkce navázán na typ orgánu. K tabulce typ_funkce je uvedeno, že "Tabulka definuje typ funkce v orgánu - pro každý typ orgánu jsou definovány typy funkcí.".

Vazba mezi typem funkce a typem orgánu ale v modelu chybí, takže je nutno ji dodělat.

**Comment by psiotwo** [comment]
Má smysl nechávat pro případné budoucí oživení modelování agendy PSP?
