### ISSUE TITLE
V-SGoV Jméno právnické osoby

### ISSUE THREAD

**Issue by dknespl** [opendata-mvcr/ssp#21]
Jako vhodnější pojem pro jméno právnické osoby se mi jeví "Název", viz např. § 132 zákona č. 89/2012 Sb. občanský zákoník (nový)

**Comment by psiotwo** [comment]
Přidán "název" jako kontextuální synonymum, identifikační název zachován stejný.

Pojem "Název právnické osoby" podle § 132 zákona č. 89/2012 Sb. občanský zákoník bude modelován v legislativním slovníku tohoto zákona.
