### ISSUE TITLE
Umístnění není navázané na Turistický cíl a Sportovište

### ISSUE THREAD

**Issue by blcham** [opendata-mvcr/ssp#216]
OFN Sportoviště i OFN Turistické cíle deklarují, že jsou navázané na umístňení. Tato vazba však neexistuje v SGoV. Umístnění je navázano jenom na Událost, která však není nadtřídou Turistického cíle ani Sportoviště:

![image](https://user-images.githubusercontent.com/3962237/106010152-6aaef800-60b9-11eb-85b4-aa1467c06a53.png)

**Comment by psiotwo** [comment]
![image](https://user-images.githubusercontent.com/1140626/107525287-fabf6800-6bb6-11eb-8575-f39f2cb8e6fd.png)
![Uploading image.png…]()

**Comment by blcham** [comment]
@psiotwo :+1: 

Uz se to zobrazuje ve formulari.

![Selection_364](https://user-images.githubusercontent.com/3962237/107585349-5d882200-6bfe-11eb-8138-73f07b72aac2.jpg)
