### ISSUE TITLE
Pravnická osoba nemá nadtřídu se stereotypem Kind

### ISSUE THREAD

**Issue by blcham** [opendata-mvcr/ssp#218]
**Motivace:** Potřebuji vědět, že právnicka osoba a fyzická osoba má různy princip identity  abychom mohli poskytnout validaci OFN.  Příklad z turistického cíle (Fyzicka osoba dedí od kindu Člověk, no Osoba takovou nadtřídu nemá):

![image](https://user-images.githubusercontent.com/3962237/106010975-528ba880-60ba-11eb-92f4-1761d62164ca.png)

**Comment by psiotwo** [comment]
Current status of person modeling:
![image](https://user-images.githubusercontent.com/1140626/106390200-84b54700-63e7-11eb-94b0-2927a2d9363e.png)

FYI @martinnec .
