### ISSUE TITLE
V-SGoV Křestní jméno

### ISSUE THREAD

**Issue by dknespl** [opendata-mvcr/ssp#22]
Pojem "Křestní jméno" je archaický, současná legislativa jej nezná. Vhodnější pojem pro jméno fyzické osoby je pouze "Jméno"

**Comment by psiotwo** [comment]
Rozumím. Přemýšlím, zda "Jméno" nemůže být často chápáno i jako (Křestní) jméno a příjmení dohromady. 

Lze tyto dva významy nějak vhodně rozlišit? (např. Wikipedie nabízí ještě pojem "Rodné jméno" https://cs.wikipedia.org/wiki/Rodn%C3%A9_jm%C3%A9no, ale netuším, zda je dostatečně zaužívaný).

I kdybychom zvolili nějaký delší popisek pro (Křestní) jméno, bude stále možné k tomuto pojmu připojit i popisek kratší (např. Jméno) vhodný pro zobrazování v určitém kontextu (např. ve formuláři, kde se vyplňují samostatná políčka "Jméno" a "Příjmení") a ponechat plný název (např. Rodné jméno) pro případy, kdy takový kontext chybí (např. formulář, kde se vyplňuje pouze (Křestní) jméno  a již ne příjmení (nevím, zda takový je), nebo kde je kontext přeurčený (např. formulář, kde se vyplňuje (Křestní) jméno, Příjmení a volitelně/alternativně (celé) jméno).

Omlouvám se za delší úvahu.

**Comment by dknespl** [comment]
Dobrý den,

 

Dle legislativy:

Matriční zákon https://www.zakonyprolidi.cz/cs/2000-301#p14 zná „jméno, popřípadě jména a příjmení dítěte“.

NOZ to má trochu jinak, zná „osobní jméno“ viz https://www.zakonyprolidi.cz/cs/2012-89#p77, jménem pak rozumí osobní jméno a příjmení dohromady.

Dále:

ZoZR je podle matriky, tj „jméno, popřípadě jména a příjmení“ https://www.zakonyprolidi.cz/cs/2012-89#p77

Cizinecký zákon ve shodě s matričním - „jméno, popřípadě jména a příjmení“ https://www.zakonyprolidi.cz/cs/1999-326#p158

O Evidenci obyvatel - „jméno, popřípadě jména a příjmení“ https://www.zakonyprolidi.cz/cs/1999-326#p158

Atd. většinou tedy „jméno, popřípadě jména a příjmení“ s jediným rozdílem toho NOZ.

 

Termín „Rodné“ se používá pro příjmení, ve smyslu „za svobodna“, nikoliv pro jméno.

Křestní jméno současná česká legislativa nezná.

 

Pak jsem psal ještě připomínku ke Jménu resp.

 

Názvu u právnické osoby.

 

Dělám momentálně pro OHA na návrhu sdílených definic základních prvků pro XML schémata pro technickou strukturu údajů pro RPP. Přivítal bych, kdybyste měl čas a chuť, si o tom popovídat a sladit RPP a OpenData

 

S pozdravem

 

David Knespl

NAKIT 

Tel. 720 437 963

 

 

Od: Petr Křemen <notifications@github.com>
Příjemce odpovědi: opendata-mvcr/ssp <reply@reply.github.com>
Datum: středa 25. března 2020 8:15
Komu: opendata-mvcr/ssp <ssp@noreply.github.com>
Kopie: dknespl <david.knespl@knespl.com>, Author <author@noreply.github.com>
Předmět: Re: [opendata-mvcr/ssp] V-SGoV Křestní jméno (#22)

 

Rozumím. Přemýšlím, zda "Jméno" nemůže být často chápáno i jako (Křestní) jméno a příjmení dohromady.

Lze tyto dva významy nějak vhodně rozlišit? (např. Wikipedie nabízí ještě pojem "Rodné jméno" https://cs.wikipedia.org/wiki/Rodn%C3%A9_jm%C3%A9no, ale netuším, zda je dostatečně zaužívaný).

I kdybychom zvolili nějaký delší popisek pro (Křestní) jméno, bude stále možné k tomuto pojmu připojit i popisek kratší (např. Jméno) vhodný pro zobrazování v určitém kontextu (např. ve formuláři, kde se vyplňují samostatná políčka "Jméno" a "Příjmení") a ponechat plný název (např. Rodné jméno) pro případy, kdy takový kontext chybí (např. formulář, kde se vyplňuje pouze (Křestní) jméno a již ne příjmení (nevím, zda takový je), nebo kde je kontext přeurčený (např. formulář, kde se vyplňuje (Křestní) jméno, Příjmení a volitelně/alternativně (celé) jméno).

Omlouvám se za delší úvahu.

**Comment by psiotwo** [comment]
Ticket zavírám. Křestní jméno ve V-SGoV nevadí. Legislativní pojmy budou zavedeny v příslušných legislativních slovnících.
