### ISSUE TITLE
Vytvořit "pojmenovaný prvek" ve V-SGoV

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ssp#297]
Napříč různými use cases se objevuje potřeba specializovat typ prvků, který zavádí obecné vlastnosti pro pojmenování a popis prvků. Čili je nutno ve V-SGoV zavést "pojmenovaný prvek".

**Comment by psiotwo** [comment]
Already present - reused the same notion (didn't find any potential issue with this). Done.
