### ISSUE TITLE
Deleted participant of a relationship type still present in the OWL export of the model

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ssp#351]
For example

https://github.com/opendata-mvcr/ssp/blob/0699e687f1e12e66dce2309bd97febd63a34e00d/content/g-sgov/g-sgov-%C4%8Das/g-sgov-%C4%8Das-model.ttl#L2629

This range should not be in the model. It was deleted from the model (see workspace OFN Časové okamžiky a intervaly > Časová specifikace > má den v týdnu.

Maybe some residuum from the old modeling times?

**Comment by psiotwo** [comment]
fixed.
