### ISSUE TITLE
Slovník, glosář a model generované z Modelia nemají label

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ssp#5]
V aktuálním exportu SGOV pro RPP nemá žádný legislativní ani agendový label vygenerovaný pro slovník, glosář ani model.

**Comment by psiotwo** [comment]
Dtto jako #6. Anotace v modelio negenerují literály bez jazyka a jazyk se zatím musí vždy uvést v literálu - syntax je stejná jako pro název pojmu (viz celý label property "název pojmu").

Ale co chybí je tento hint, jak tvořit validní hodnoty v těchto polích, dát i pro název slovníku - to doplním.
