### ISSUE TITLE
V případě, že prvek nemá v Modeliu definován název v property 'název' z OntoUML modulu, mohl by se pro rdfs:label / skos:prefLabel brát standardní název z Modelio properties

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ssp#6]

**Comment by psiotwo** [comment]
K anotaci slovníku bych ještě musel přidat default jazyk, ve kterém ten label generujeme. Výhledově prozkoumám.

Syntax pole název umožňuje přímo jazykové varianty nastavit - jedná se o seznam RDF literalů oddělený čárkami, tedy např.: "osoba"@cs, "person"@en.

**Comment by psiotwo** [comment]
Vyřešeno, dle komunikace s MB.
