### ISSUE TITLE
Export z Modelia je v ANSI, je nutný UTF8

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ssp#7]
Kódování UTF8 je standard pro Turtle apod. S diakritikou to pak triplestore nenačte, když to není UTF8

**Comment by psiotwo** [comment]
OK, prozkoumám. Mělo by to být UTF-8, pokud není, je to bug.

**Comment by psiotwo** [comment]
V Linuxu [1] mi to správně generuje UTF-8. Prosím pošli ukázkový výstup. Výstupy, generované na [1] jsou v adresáři SGOV ve mnou nově nahrané verzi SGOV.zip

[1] Version 3.6.01, Build: 201703061558, System: linux (4.15.0-38-generic), Architecture: x86_64

**Comment by jakubklimek** [comment]
@psiotwo Na Linuxu je UTF-8 default. Na Windows ne. Je tedy třeba to explicitně specifikovat jako UTF-8. Něco jako 
```java
FileOutputStream fos = new FileOutputStream("File2Hex.txt");
OutputStreamWriter osw = new OutputStreamWriter(fos, "UTF-8");
```

**Comment by psiotwo** [comment]
To máš pravdu. Aktuální verze tedy force-serializuje do "utf-8".
