### ISSUE TITLE
IRI ustanovení právního předpisu uvedené v metadatech prvku je Literal

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ssp#9]
IRI ustanovení právního předpisu uvedené v metadatech prvku by mělo být exportováno jako RDF Resource.

**Comment by psiotwo** [comment]
Done.

**Comment by martinnec** [comment]
Právních předpisů může být více, tj. IRI oddělené čárkou.

**Comment by psiotwo** [comment]
Done.
